---
apiVersion: v1
kind: ConfigMap
metadata:
   name: nwapp-cm
   labels:
      app: northwind

data:
   DB_USER: root
   DB_HOST: nwdb-svc.nw.svc.cluster.local # FQDN

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nwapp-deploy
   labels:
      app: northwind

spec:
   replicas: 2
   selector:
      matchLabels:
         app: nwapp-pod
   template:
      metadata:
         name: nwapp-pod
         labels:
            app: nwapp-pod
      spec:
         containers:
         - name: nwapp-container
           image: chukmunnlee/my-nwapp:v1
           imagePullPolicy: IfNotPresent
           resources:
              requests:
                 cpu: "200m"
                 memory: "32Mi"
              limits:
                 memory: "64Mi"
           env:
           - name: DB_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: nw-secret
                   key: MYSQL_ROOT_PASSWORD
           - name: INSTANCE_IP_ADDRESS
             valueFrom:
                fieldRef:
                   fieldPath: status.podIP
           envFrom:
           - configMapRef:
               name: nwapp-cm
           ports:
           - name: nwapp-port
             containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
   name: nwapp-svc
   labels:
      app: northwind

spec:
   type: ClusterIP
   selector:
      app: nwapp-pod
   ports:
   - name: nwapp-svc-port
     port: 3000
     targetPort: nwapp-port

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: nwapp-ing
   labels:
      app: northwind

spec:
   rules:
   - host: nw.167.172.6.189.nip.io
     http:
        paths:
        - path: /
          backend:
             serviceName: nwapp-svc
             servicePort: nwapp-svc-port

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
   name: nwapp-hpa
   labels:
      app: northwind

spec:
   minReplicas: 1
   maxReplicas: 4

   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nwapp-deploy

   metrics:
   - type: Resource
     resource:
        name: memory
        target:
           type: Utilization
           averageUtilization: 80
   - type: Resource
     resource:
        name: cpu
        target:
           type: Utilization
           averageUtilization: 15
