---
apiVersion: v1
kind: Pod
metadata: 
 name: fortune-po
 labels:
  app: fortune

spec:
 containers:
 - name: fortune-container
   image: chukmunnlee/fortune:v1
   imagePullPolicy: IfNotPresent
   ports: 
   - containerPort: 3000
  